discovery.uri=http://presto-coordinator:8080
presto.version=testversion
http-server.http.port=7777
system-memory-gb=2
shutdown-onset-sec=1
runtime-metrics-collection-enabled=true

# Reduce task concurrency to lower memory usage
task.max-drivers-per-task=1

# Reduce amount of memory that aggs can hold on to
task.max-partial-aggregation-memory=1GB

# ease debugging by reducing number of threads
http-server.num-io-threads-hw-multiplier=0.01
http-server.num-cpu-threads-hw-multiplier=0.01