discovery.uri=http://presto-coordinator:8080
presto.version=testversion
http-server.http.port=7777
system-memory-gb=2
shutdown-onset-sec=1
runtime-metrics-collection-enabled=true

# Reduce task concurrency to lower memory usage
task.max-drivers-per-task=1

# Reduce amount of memory that aggs can hold on to
task.max-partial-aggregation-memory=1GB


# Floating point number used in calculating how many threads we would use
# for Exchange HTTP client CPU executor: hw_concurrency x multiplier.
# 1.0 is default.
exchange.http-client.num-cpu-threads-hw-multiplier=0.01

# Floating point number used in calculating how many threads we would use
# for Exchange HTTP client IO executor: hw_concurrency x multiplier.
# 1.0 is default.
exchange.http-client.num-io-threads-hw-multiplier=0.01

# Floating point number used in calculating how many threads we would use
# for HTTP IO executor: hw_concurrency x multiplier. 1.0 is default.
http-server.num-io-threads-hw-multiplier=0.01

# Floating point number used in calculating how many threads we would use
# for HTTP CPU executor: hw_concurrency x multiplier. 1.0 is default.
http-server.num-cpu-threads-hw-multiplier=0.01

# Floating point number used in calculating how many threads we would use
# for IO executor for connectors mainly to do preload/prefetch:
# hw_concurrency x multiplier.
# If 0.0 then connector preload/prefetch is disabled.
# 0.0 is default.
connector.num-io-threads-hw-multiplier=0.01

exchange.client-threads=16
exchange.http-client.max-connections=5000
exchange.http-client.max-connections-per-server=5000
exchange.http-client.max-requests-queued-per-destination=4096

http-server.log.max-size=67108864B
http-server.log.max-history=2
http-server.threads.max=1000

log.max-history=30
log.max-size=104857600B
memory.heap-headroom-per-node=2GB

node-scheduler.max-pending-splits-per-task=2000
node-scheduler.max-splits-per-node=2000
