connector.name=hive-hadoop2
hive.metastore=file
hive.metastore.catalog.dir=file:/prestissimo/docker-setup/hive-metastore
hive.allow-drop-table=true
hive.parquet.optimized-writer.enabled=true
hive.parquet.writer.version=PARQUET_2_0
hive.storage-format=PARQUET

hive.max-initial-splits=1
hive.max-initial-split-size=1TB
hive.max-split-size=1TB
hive.split-loader-concurrency=32
hive.max-outstanding-splits=1800

hive.pushdown-filter-enabled=true
hive.parquet.pushdown-filter-enabled=true
